# Make sure we run container based worker
sudo: false
dist: trusty

language: python
python:
- '2.7'
- '3.6'

install:
- pip install pipenv
- pipenv install
- pipenv check

# This belong to default stage 'test'
script:
- pipenv run python -m compileall clairmeta
- pipenv run python -m unittest discover -s tests

# Stage conditions
stages:
  - name: test
    if: type IN (pull_request) OR tag =~ ^1
  - name: deploy
    if: tag =~ ^1

# Jobs
jobs:
  include:
  - stage: deploy
    script:
    - echo "Deploying..."
    - python setup.py sdist bdist_wheel --universal
    deploy:
      - provider: releases
        skip_cleanup: true
        api_key:
          secure:     NnuZ3rpD3VgJ+E0SQvfkP23SWyml4z/QBWJMHbT1mnacS7QPHYmg4kU3NBjd4RCXAorwD/PRZoexcISZsyaok2h5ck/Y7nNkQzzE6m+qBSOb4G/ae1+La6X8KuvuxqvJb9t084lwHdmPfTCLE32dz3IYf1ZHmQJ3kKOV0tPK+GgBEEr/tgyKQ38ktCGEq5Fg52zfzOgiPWkmkp9PZjuZBf47FpXAUj8jrkcgFLJmWVek7qd9igDLcO7RVISTLWlpgc/OLKIyiiOfXywPZcGlN6zI3ynR8DpyQ0gV0wsVacAwxuLKpZ3Ill93wvclOhIMQdGfOhLyOV1UyC8ud/nBGh9ScaP7UR0gAsJqile3huRHgwV2tgXbkExUy2zpEo/jn7CbBMCh2Wt6TJSeQZolN6eimgs3Io0Jke+w6W29WCPzhntNpwWtI6KbK8s/VCH9pD5uSwTMBUeAPQpj/2XV6SDfgHZkP7m2qZeRFTxwr4Af9W6l7otwF8d2VdxCbpitMUwviQeZrWbaacevBXJlri+W/XH/vFxo1LHJeETYpg+663rlqApCt+UpMyBP3cd4pNzddCY2PUycjWuwu9SDtf180iK4Sj4gsllYm2D5xG1YmZnCqw5xzXthTgZ+MpbF/619dNLZQxfJDBMchj9wBNiFpHKOoJPerIHHqs132hA=
        file_glob: true
        file: dist/*
        on:
          branch: master
          tags: true
      - provider: pypi
        user: ymagis
        password:
          secure: PPn5Yq4sr4fkKODPLRv/4Z1Ljk+KLb48nH7WHdYTUNuoKDEVQ/bQ9H4dyOmQM9JHE53p5gpWobT4DhVaB6GZOw5WycZEbP/Z24fsa3GJZoezARV6bYBFKGC6Y+qwjeh91tHBF0Iq6qMGNFn1J9BJ2YIdyDJxtgxOaHIXNR0wjc0GrUNQi1KIBGQWXcqU3oqd44Nr0tryTDiIgaiccZ2VJTGVh1by7RpPWIJrZVlOHWj/mELXQ4Ar0Jy2DZDKtctVJwfNK0H6eCxlJ7fg9RpplXqQ8OYERrIssWP3mkCUYyB0MOmZu/F1r1mfZ8pdWqnce6mMB4BIlQBb7xeSKwqTB34UzD3+WLm+2AYOXNLLQHuAjOojJ6diis6vqDYKPMcIOE1ezJILd5UKPEUS2t/+Fuvden2q+mXScupapxObKJzTl7KZnWZvgRmh7tN4m8rs6IbDRqAZbg/Dv4gk3LDCoLPwnRpkd/MCMQ5cgqBNmD27MXhMHgKeD7CoZshhzAtAEU3bvhh7RdjlidhdiQ/SnmX2s9PEzGSVWXzkkx4ON1/ezkA0wkD9POjmFDAYq7/eEfmE+7zpGlqPFZYTzoq4oa6six8ZKjrdd/QJP0Hq2Tn5FMyrABiu9ZO2w3PCLPCrQa417I4f+BXHGmSc+sG49y7i4qnKHw9c7aRdGzl6NQc=
        distributions: sdist bdist_wheel
        on:
          branch: master
          tags: true