
sudo: required
services:
  - docker
dist: trusty

language: python
python:
- '2.7'
- '3.6'

env:
  global:
    - BINTRAY_USER=ymagis
    - BINTRAY_ORG=ymagis
    - BINTRAY_REPO=Clairmeta
    - secure: "IKV4DSNedoMP/uTPWHVnJp2E/K9JDKu/InMJGQkQR5hreJGpWw6Q2OWo9qIDXQ0PXX9k5Aw3k+w+/Utp6+lNHUzMuKk92CCZ5ieolTgzYzaN/eYDIPVnQhE/S7v06liQn8f1IgDl+/brEmDmWQm73aYGjlkt1jBWma0ZOXxPC3eBhUMIc/5pWJXwnGRSNREW1LxLami+C7uN02qZwd1eHU+RU71bt5uYFHKrhMHB40MGQx20YpJ/yMcGhhXNZHSvmzKIus27oPreP1hFc22xO3Mfjq4Vgz9qoEQolJZPe/v2bHtMKooTPAfeTAI36oNpiTvR3SHEYX3uVjOIcuG3QCNPkhXEWIgjUtj3SVlM19Nvb0qtGkQVZnVXHtRZKKdzWbnOYI0zwWj3OEhyCzUbsadUFqiWJ7FZwtkYCT7Kmdi6UzPAh2L7/gSOECj4RZgZgpjaApJ3ruSMz/pMzDq1U+Q25esj/JS9vJU8eaSrOjD2Fk1RxhI8WXMZutb6dcLo0eQIrYo5LN7UOVRzd19KoliWMOmUQrTYlSU08CK0IVog4+rVlw8PjJ71LP/+w/5IZtCyhkYqmFSdwdNkQNKrydQE7jNZ6iZnkMmx9LLzwQ2HbamyjCQeoGHuK7SVlMXgkg0msqiyj5lpPnc5oZaTDCLJBUY9cDjxSYQDPOR7+/M="

install:
- pip install pipenv
- pipenv install
- pipenv check

# This belong to default stage 'test'
script:
- pipenv run python -m compileall clairmeta
- pipenv run python -m unittest discover -s tests

# Stage conditions
stages:
  - name: test
    if: type IN (pull_request) OR tag =~ ^1
  - name: deploy
    if: tag =~ ^1
  - name: packaging
    if: tag =~ ^1

# Jobs
jobs:
  include:
  - stage: packaging
    script:
    - /bin/bash .travis/build_env.sh
  - stage: deploy
    script:
    - echo "Deploying..."
    - python setup.py sdist bdist_wheel
    deploy:
      - provider: releases
        skip_cleanup: true
        api_key:
          secure:     NnuZ3rpD3VgJ+E0SQvfkP23SWyml4z/QBWJMHbT1mnacS7QPHYmg4kU3NBjd4RCXAorwD/PRZoexcISZsyaok2h5ck/Y7nNkQzzE6m+qBSOb4G/ae1+La6X8KuvuxqvJb9t084lwHdmPfTCLE32dz3IYf1ZHmQJ3kKOV0tPK+GgBEEr/tgyKQ38ktCGEq5Fg52zfzOgiPWkmkp9PZjuZBf47FpXAUj8jrkcgFLJmWVek7qd9igDLcO7RVISTLWlpgc/OLKIyiiOfXywPZcGlN6zI3ynR8DpyQ0gV0wsVacAwxuLKpZ3Ill93wvclOhIMQdGfOhLyOV1UyC8ud/nBGh9ScaP7UR0gAsJqile3huRHgwV2tgXbkExUy2zpEo/jn7CbBMCh2Wt6TJSeQZolN6eimgs3Io0Jke+w6W29WCPzhntNpwWtI6KbK8s/VCH9pD5uSwTMBUeAPQpj/2XV6SDfgHZkP7m2qZeRFTxwr4Af9W6l7otwF8d2VdxCbpitMUwviQeZrWbaacevBXJlri+W/XH/vFxo1LHJeETYpg+663rlqApCt+UpMyBP3cd4pNzddCY2PUycjWuwu9SDtf180iK4Sj4gsllYm2D5xG1YmZnCqw5xzXthTgZ+MpbF/619dNLZQxfJDBMchj9wBNiFpHKOoJPerIHHqs132hA=
        file_glob: true
        file: dist/*
        on:
          branch: master
          tags: true
      - provider: pypi
        skip_cleanup: true
        user: ymagis
        password:
          secure: z+NBy5v4tPyROoqiZhtlPPmFYPJj8UB8cBmr0Yu2ka3+Zp+w/ouiQJTY8jZgMs0vvQ96DaGhC1OYVKdN2hV+vvzwfeZHmDbqMG5FAEeFndmnAwMnSrK02Ux6x5RVme90ji9x1fQYjG1eo+opSjm36QI8Lj7r8OXXdCsWumstpGeFQ1z9LrP5/5eGMXHYniFLJoDIWmR3oBxngxtj+2hbFOhTDfxSzfkNH6XLmNcGoUbpTYrmFNjHQtQod4OL25ZmWJjD01sxKXW9q/BIrUVHmGGoXnMtUPJGRm/LN0+3FOllJouhKd+GcLFW2eBQwRG4w3Ztz3M6PYXKt9ayI/Xb/zfspxq55qq3+s+wR94ZzgVWWydH1d1v0BIwrHs/mR9aBpHxuFa1nu4BRz3hLonVuw9/h96KmaFfhjthhVspNq4YnV6gzJmxenz0trI9JZxkjA+x33QUf3/zaKM1k+9zJESCng8KZWlDqxF41HSEFA+ZaYic9dH9fFc88VCXIQ1dyswOkuncPNPi7Dcj09IoKbyUqOlUFCFa3vb4YDtMt/ZAGnTR3KkLQjkJqTyQ6z5TC8Nwn+BM+vC9df3ckxv+ogyPM/YILlcEFmEl2PV2k0xUv62s1t08sU0eSB3WVewuNQwrkQt4OYwhjaHYKb0ThlHY74kyOaiSV4C5ygtd/S8=
        distributions: sdist bdist_wheel
        on:
          branch: master
          tags: true